# Generated by Django 4.2.15 on 2024-09-04 00:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aplication", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voiceanswer",
            name="status",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name="voicequestion",
            name="status",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
